import json, os

os.makedirs(r"d:\CODING TOOLS\ANTIGRAVITY\dutchedtech\backend\data\temp_deep_reports", exist_ok=True)

companies = [
  {
    "id": "lingo_llama",
    "data": {
      "report_md": "# 🦙 Lingo Llama - Stratejik Analiz Raporu\n\n## 📌 Firma Hakkında Derinlemesine Özet\nEindhoven merkezli **Lingo Llama**, 2-10 çalışana sahip erken aşama bir girişimdir. Hedef kitlesi çocuklar olup, hikaye anlatımı ve oyunlaştırma üzerinden yabancı dil eğitimi vermeyi misyon edinmişlerdir. Karakter yaratımı ve maskot kullanımını bir araç olarak benimseyerek çocukların dil öğrenme motivasyonunu artırırlar. Pazardaki rakiplerine kıyasla saf bir \"ezber\" mantığı yerine bağlamsal ve görsel bir evren inşa etmeye odaklanmışlardır.\n\n## 🚀 Öne Çıkarılması Gereken Yetenekler\n*   **Görsel Evren İnşası (Duygu Kabaiş):** Bugüne dek 100'den fazla basılı kitapta yer alan illüstrasyon tecrübesiyle Lingo Llama'nın maskot dünyası genişletilebilir, UI/UX pedagojik açıdan sıcak ve sevecen bir yapıya büründürülebilir. (Örn: *Smart Stars* ve *Smart Cookies* projeleri örnek gösterilmelidir).\n*   **Pedagojik Senaryolaştırma (Serhat Kabaiş):** 22 yıllık İngilizce öğretmeni perspektifiyle oyun içi bölümlerin bağlamsal diyaloglarını ve Connectivism temelli etkileşimlerini kurgulama yeteneği.\n\n## 🤝 Potansiyel İş Birliği Alanları (Ekosistem Raporları Işığında)\nEindhoven teknoloji ekosistemi yüksek donanım ve yazılım kümelenmesine sahiptir. Lingo Llama özelinde Duygu Hanım'ın mevcut karakter tasarımlarının Lingo Llama platformunda animasyonlaştırılması için \"Kreatif Sanat Yönetmenliği\" hizmeti sunulabilir. Ayrıca, Serhat Bey'in \"AI MOSAIC\" projesindeki dil edinim vizyonuyla, uygulamaya Sokratik özellikli oyunlaştırılmış LLM diyalogları entegre edilmesi önerilebilir.\n\n## 💡 Görüşme Tüyoları\n*   Duygu Hanım'ın portfolyosunu (tablet üzerinden) interaktif hikaye formatında hazır tutun.\n*   Erken aşama bir girişim oldukları için katı bütçeler yerine, kâr paylaşımlı \"ortak dil kitabı / hikaye modülü\" yayınlama fikrini cazip bir teklif olarak sunun.\n*   Tasarımlarınızın Hollanda dışı (özellikle Türkiye ve çevresi) pazarlara lokalizasyonda büyük avantaj sağlayacağını vurgulayın.\n\n## ❓ Sorulabilecek Stratejik 2 Soru\n1. *Platformunuzdaki hikaye anlatımının görsel dilini tasarlarken mevcut kapasitenizle en çok tıkandığınız nokta neresi ve biz bu kreatif darboğazı nasıl aşabiliriz?*\n2. *Dil eğitimini sınıf içi bir müfredatla hibrit hale getirmeyi (B2B okul satışları) planlıyor musunuz, öğretmen asistanı panelinize pedagojik bir değer katabilir miyiz?*",
      "why_recommended_tr": "Lingo Llama, karakter odaklı dil öğrenimi ve oyunlaştırma üzerine kuruludur. Duygu Hanım'ın 100'ü aşkın çocuk kitabı illüstrasyonu ve Smart Cookies seti tecrübesi, markanın görsel dünyasına doğrudan değer katacaktır. Aynı zamanda Serhat Bey'in İngilizce öğretmenliği deneyimi, pedagojik oyun kurgusunda kusursuz bir uyum sağlar.",
      "why_recommended_en": "Lingo Llama is built on character-driven language learning and gamification. Duygu's experience illustrating over 100 children's books and her work on the Smart Cookies set directly adds value to their visual universe. Serhat's English teaching background ensures a perfect pedagogical fit.",
      "strengths_tr": "Görsel hikaye anlatıcılığı (Duygu) ile dil pedagojisinin (Serhat) eşsiz kombinasyonu. Çizimlerin interaktif bir uygulamaya entegre edilmesi için ideal bir test ortamı.",
      "strengths_en": "A unique combination of visual storytelling (Duygu) and language pedagogy (Serhat). Ideal testbed to integrate static illustrations into an interactive app.",
      "weaknesses_tr": "Start-up aşamasında olmaları (2-10 çalışan), büyük ölçekli ve yüksek bütçeli içerik siparişleri vermelerini zorlaştırabilir. Ortak proje hibe başvuruları değerlendirilebilir.",
      "weaknesses_en": "Being early-stage (2-10 employees) limits their budget for large-scale content commissions. Joint grant applications could be a workaround."
    }
  },
  {
    "id": "gynzy",
    "data": {
      "report_md": "# 🎓 Gynzy - Stratejik Analiz Raporu\n\n## 📌 Firma Hakkında Derinlemesine Özet\n100.000'den fazla öğretmen tarafından aktif kullanılan Eindhoven merkezli **Gynzy**, ilkokul ekosisteminin devlerindendir. Temel ürünleri akıllı tahtalar üzerinden sunulan etkileşimli ders materyalleridir. Misyonları öğretmenlerin ders hazırlık süreçlerindeki idari ve operasyonel yükünü en aza indirerek onları asıl işleri olan \"öğretmeye\" odaklamaktır.\n\n## 🚀 Öne Çıkarılması Gereken Yetenekler\n*   **Sınıf Yönetimi Pedagojisi (Serhat Kabaiş):** 22 yıllık doğrudan saha tecrübesiyle, öğretmenlerin sınıf içindeki kaos anlarında bir yazılımdan ne beklediğini çok net bilmeniz.\n*   **B2 Dijital Yetkinlik ve Yapay Zeka Entegrasyonu:** AI MOSAIC projenizin kanıtladığı üzere, sınıfta LLM'lerin asistan olarak kullanımı, Gynzy'nin gelecekteki ürün güncellemeleri için mükemmel bir vaka çalışmasıdır.\n\n## 🤝 Potansiyel İş Birliği Alanları (Ekosistem Raporları Işığında)\nGynzy'nin akıllı tahta widget kütüphanesine, \"Assos Bilim Şenliği\" atölyelerinden süzülmüş, öğrencileri harekete geçirecek yeni nesil \"STEAM Widget'ları\" teklif edilebilir. Ek olarak, Duygu Hanım Gynzy arayüzündeki standart oyunlaştırma araçlarına \"Premium Görsel Paketler\" (özel tatil temaları, yeni karakter setleri) tasarlayarak platformun görsel canlılığını artırabilir. Uluslararası vizyon olarak, yazılımın Türk pazarındaki potansiyel lansmanı için pedagojik lokalizasyon partnerliği sunulabilir.\n\n## 💡 Görüşme Tüyoları\n*   Büyük bir firma olmaları nedeniyle kurumsal bir B2B dil kullanın; \"biz size şu hizmeti satabiliriz\" yerine, \"Hollanda EdTech pazarında öğretmen benimsemesini artıracak şu pedagojik UX araştırmalarına sahibiz\" yaklaşımını sergileyin.\n*   Tahta üzerindeki mevcut araçların çocuklarda yarattığı \"bilişsel yükü (cognitive load)\" tartışarak, Duygu Hanım'ın görsel sadelik ve pedagojik uyum kasını ön plana çıkarın.\n\n## ❓ Sorulabilecek Stratejik 2 Soru\n1. *Öğretmenlerin ders hazırlık sürecini kısaltma misyonunuzda, Generative AI (Üretken Yapay Zeka) entegrasyonu için mevcut yol haritanızda dışarıdan pedagojik prompt validasyonuna ihtiyaç duyuyor musunuz?*\n2. *Mevcut pazarınızda doymuşluğa ulaştığınızda, ürünü Güney Avrupa/Orta Doğu gibi daha farklı sınıf dinamikleri olan bölgelere adapte etmek için lokal pedagoji ortaklıkları arayışınız var mı?*",
      "why_recommended_tr": "Gynzy, sınıf içi etkileşimli tahta yazılımlarında bir endüstri standardıdır. Serhat Bey'in 22 yıllık öğretmenlik vizyonu, AI MOSAIC gibi AB etiketli projeleri ve ders planı süreçlerini otomatize etme ilgisi, firmanın 'Öğretmenlere Zaman Kazandır' felsefesiyle muazzam örtüşmektedir.",
      "why_recommended_en": "Gynzy is an industry standard for interactive whiteboard software. Serhat's 22-year teaching vision, his AI MOSAIC project, and focus on lesson plan automation strongly align with their 'Give Teachers Time to Teach' philosophy.",
      "strengths_tr": "Öğretmenin sınıf içi donanım ve yazılımlarla olan bağını (Connectivism) doğrudan tecrübe etmeniz. Ürünün son kullanıcı odaklı geri bildiriminde en yüksek yetkinlik.",
      "strengths_en": "Direct classroom experience with interactive tech. Top-tier competence in end-user feedback and pedagogical software integration.",
      "weaknesses_tr": "51-200 kişilik olgun bir ürün olmaları, yeni dış vizyonların entegre edilmesini yavaşlatabilir. İletişim doğrudan karar vericilerle olmalıdır.",
      "weaknesses_en": "As a mature 51-200 FTE scale-up, integrating external visions might be slow. Outreach must target C-level or Product Directors."
    }
  },
  {
    "id": "wizenoze_corp",
    "data": {
      "report_md": "# 🔍 Wizenoze - Stratejik Analiz Raporu\n\n## 📌 Firma Hakkında Derinlemesine Özet\nAmsterdam merkezli (11-50 FTE) **Wizenoze**, öğrencileri internetteki manipülatif veya anlaşılmaz metinlerden koruyan bir EdTech yapay zeka arama motorudur. Öğrencinin okuma seviyesini tespit edip arama sonuçlarındaki metinleri bu seviyeye uygun bir formata getirir (Kürasyon). Sistemleri büyük ölçüde karmaşık NLP (Doğal Dil İşleme) algoritmalarına ve B2B yayıncılık ortaklıklarına dayanmaktadır.\n\n## 🚀 Öne Çıkarılması Gereken Yetenekler\n*   **Bağlantıcılık (Connectivism) Uzmanlığı (Serhat Kabaiş):** Ağ üzerinden öğrenme kuramının temelini oluşturan bilgi düğümleri (nodes) arasında bağlantı kurma becerisi, Wizenoze'un bilgi kürasyonu vizyonuyla felsefi olarak mükemmel örtüşür.\n*   **Akademik Pedagoji:** Öğrenci okuduğunu anlama seviyelerinin algoritmalara değil, gerçek sınıf ortamındaki \"dijital etnografik\" gözlemlere dayandırılarak test edilmesi.\n\n## 🤝 Potansiyel İş Birliği Alanları (Ekosistem Raporları Işığında)\nWizenoze ürünlerinin sınıf içinde nasıl tüketildiğini (öğrencinin ekranla olan kültürel ve antropolojik ilişkisini) incelemek üzere Serhat Bey'in yüksek lisans tezini veya \"eTwinning\" ağındaki uluslararası okullarını bir \"Test-Bed\" (deney sahası) olarak sunabilirsiniz. Wizenoze teknolojisi, TÜBİTAK bilim atölyelerinde kırsal bölgelerdeki öğrencilerin internet araştırmalarında kullanılarak bir vaka çalışmasına (case study) dönüştürülebilir.\n\n## 💡 Görüşme Tüyoları\n*   Veri bilimi ağırlıklı bir ekip oldukları için pedagojik terminolojiyi teknolojiye bağlayarak anlatın. (Örn: \"Algoritmanızın ürettiği Flesch-Kincaid skorunun, sınıf içi dijital etnografi gözlemlerimizle örtüşüp örtüşmediğini doğrulayabiliriz.\")\n*   Duygu Hanım'ın UI tecrübesini, metinlerin okunabilirliğini artıran tipografi ve ekran yerleşimi tavsiyeleri olarak entegre edin.\n\n## ❓ Sorulabilecek Stratejik 2 Soru\n1. *Yapay zeka modellerinizin farklı dillerde ve kültürlerdeki (cross-cultural) okuma alışkanlıklarına adaptasyonu aşamasında, 'Dijital Antropoloji' odaklı saha testleri uyguluyor musunuz?*\n2. *Wizenoze'un içerik ekosistemini, öğretmenlerin kendi müfredatlarına tam entegre edebilmeleri için (Lesson planning) ne gibi yeni arayüz vizyonlarınız var?*",
      "why_recommended_tr": "Wizenoze'un internetteki bilgi yığınını öğrencilerin okuma düzeyine göre yapay zekayla filtreden geçirmesi, Serhat Bey'in 'Dijital Antropoloji' ve LLM asistanları üzerine olan akademik araştırması için üst düzey bir uygulama sahasıdır.",
      "why_recommended_en": "Wizenoze's AI-driven curation of internet content matching reading levels is a high-level application field for Serhat's academic research into Digital Anthropology and LLM assistants.",
      "strengths_tr": "İngilizce öğretmenliği tecrübesi ve B2 sertifikası. Metin okuma düzeylerinin pedagojik validasyonunu bizzat yapabilecek akademik altyapı.",
      "strengths_en": "English teaching experience and B2 certification. The academic background to practically validate text readability algorithms.",
      "weaknesses_tr": "Şirket ileri seviye veri bilimi (Data Science) ve NLP üzerine yoğunlaşmış B2B bir yapıdır. Sınıf pedagojisinin onların algoritmalarına nasıl değer katacağı somut bir dille kanıtlanmalıdır.",
      "weaknesses_en": "Highly technical B2B structure centered on NLP and Data Science. You must concretely prove how classroom pedagogy adds value to their algorithms."
    }
  },
  {
    "id": "nextgen_ai",
    "data": {
      "report_md": "# 🤖 NextGen AI - Stratejik Analiz Raporu\n\n## 📌 Firma Hakkında Derinlemesine Özet\nAmsterdam merkezli, yeni kurulmuş (2-10 çalışan) butik bir girişim olan **NextGen AI**, tamamen Z ve Alfa kuşağı çocuklarına üretken yapay zekanın (Generative AI) temellerini, prompt mühendisliğini ve temel makine öğrenimi mantıklarını atölye ve kamplar aracılığıyla aktarmayı amaçlar. Okullarla kulüp (after-school) bazlı çalışmalar yürüterek teknolojik okuryazarlığı bir adım öteye taşırlar.\n\n## 🚀 Öne Çıkarılması Gereken Yetenekler\n*   **Hazır Müfredat Gücü (Serhat Kabaiş):** TÜBİTAK 4009 \"Yapay Zekâ ile Hayalimdeki Akıllı Köy\" atölyenizle tam donanımlı, uygulanmış ve başarılı olmuş bir modeli masaya koyuyorsunuz.\n*   **İda Kaşifleri Vizyonu:** Multidisipliner bilim ve doğa etkinliklerindeki organizasyon yeteneğiniz, onların bu atölyeleri açık havada veya farklı disiplinlerle harmanlamasını sağlayabilir.\n*   **Tasarım Desteği (Duygu Kabaiş):** Soyut \"Algoritma\" ve \"Prompt\" kavramlarını çocuklara anlatmak için tasarlanmış renkli infografikler ve çalışma kâğıtları (worksheet) yaratma becerisi.\n\n## 🤝 Potansiyel İş Birliği Alanları (Ekosistem Raporları Işığında)\nHollanda'daki yaz kampları veya okul sonrası etkinlikleri için \"NextGen AI & Edumanu\" ortak atölye paketleri oluşturulabilir. Serhat Bey, sahip olduğu B2 Educators’ Digital Competencies ve eTwinning Avrupa Kalite Etiketi belgeleriyle bu girişimin okullara girerkenki akademik/pedagojik meşruiyetini artıracak \"Baş Eğitmen (Master Trainer)\" statüsünde konumlanabilir.\n\n## 💡 Görüşme Tüyoları\n*   Atölyelerinizdeki çocukların \"Sanal Pedal\" ve \"Arduino\" projeleriyle AI'ı nasıl birleştirdiğini göstererek donanımsal zenginliğinizi anlatın.\n*   Kısıtlı bütçeleri olan hevesli bir ekip olacaklarını varsayarak, bilgi ve müfredat takası yapabileceğiniz \"pilot atölye\" teklifleri sunun.\n\n## ❓ Sorulabilecek Stratejik 2 Soru\n1. *Mevcut atölyelerinizde çocukların ekran başında geçirdikleri pasif süreyi fiziksel aktiviteye veya donanımsal üretime (Maker felsefesi) dönüştürmekte ne gibi zorluklar yaşıyorsunuz?*\n2. *Okullara sunduğunuz atölyeleri standartlaştırıp dijital bir eğitim materyaline (satılabilir kutu veya platforma) dönüştürme planınız için pedagojik bir stratejiniz var mı?*",
      "why_recommended_tr": "Çocuklara erken yaşta prompt yazımı ve yapay zeka mantığı öğretme hedefleri, Serhat Bey'in TÜBİTAK 4009 'Yapay Zekâ ile Hayalimdeki Akıllı Köy' atölyesiyle birebir aynı eksendedir.",
      "why_recommended_en": "Their goal of teaching children prompt writing and AI logic perfectly aligns with Serhat's TÜBİTAK 4009 'My Smart Village with AI' workshop.",
      "strengths_tr": "Hazır ve test edilmiş atölye senaryoları. AI MOSAIC projesi sayesinde çocuklarda AI asistanlarının kullanımı üzerine derin pedagojik birikim.",
      "strengths_en": "Ready-to-use and tested workshop scenarios. Deep pedagogical background on AI assistants from the AI MOSAIC project.",
      "weaknesses_tr": "Yeni ve küçük bir organizasyon oldukları için ciddi bir bütçeleri olmayabilir; ticari işlerden çok ortak görünürlük (PR) anlaşmaları yapılabilir.",
      "weaknesses_en": "Being a new and small club, they may lack a serious budget; partnerships might be more about joint PR and networking than immediate revenue."
    }
  },
  {
    "id": "chatlicense",
    "data": {
      "report_md": "# 📱 ChatLicense - Stratejik Analiz Raporu\n\n## 📌 Firma Hakkında Derinlemesine Özet\nUtrecht çıkışlı **ChatLicense** (13 çalışan), ebeveynlerin çocuklarına verdikleri \"ilk akıllı telefon\" sürecine rehberlik eden ödüllü bir dijital uygulamadır. Siber zorbalık, güvenli internet, dijital etik gibi çok kritik sorunları, sıkıcı uyarılar yerine interaktif mini-oyunlar ve senaryo bazlı simülasyonlarla öğretir. Hem çocukların güvenliğini sağlar hem de ebeveynleri bilinçlendirir.\n\n## 🚀 Öne Çıkarılması Gereken Yetenekler\n*   **Dijital Etnografi Alan Bilgisi (Serhat Kabaiş):** Dijital toplulukların dinamiklerini inceleyen alanınız sayesinde, çocukların WhatsApp/Snapchat benzeri ortamlardaki antropolojik davranış kodlarını çok iyi analiz edebilmeniz.\n*   **İllüstrasyon ve Karakter Gelişimi (Duygu Kabaiş):** 100+ kitaplık tecrübeyle ChatLicense evrenine \"Siber Zorba\", \"Bilgi Avcısı\" gibi çocukların duygusal bağ kurabileceği, modern ve pedagojik olarak zararsız antagonist/protagonist (kötü/iyi) karakterler kazandırma yeteneği.\n\n## 🤝 Potansiyel İş Birliği Alanları (Ekosistem Raporları Işığında)\nChatLicense'in genişleme haritasında yapay zekanın etik kullanımına (deepfake'ler, LLM halüsinasyonları) yönelik yeni bir modül (\"AI Citizenship\") gereklidir. Serhat Bey, \"AI MOSAIC\" projesindeki etik kullanım manifestolarını bu platforma bir oyun senaryosu olarak uyarlayabilir. Duygu Hanım ise uygulamanın bu yeni \"Yapay Zeka Mahallesini\" veya Türkiye/Avrupa lokalizasyonlarındaki görsel elementleri tasarlayabilir. \n\n## 💡 Görüşme Tüyoları\n*   Odak noktanız \"yasaklama/kısıtlama\" değil, \"okulsuz eğitim (unschooling)\" yaklaşımında olduğu gibi dijital alanlarda \"sorumlu özgürlük\" olsun. ChatLicense bu modern vizyonu çok sevecektir.\n*   \"Minik Aristo\" atölyesindeki (Duygu Hanım'ın yürüttüğü) felsefi tartışma ortamlarının P4C (Çocuklar için Felsefe) tekniklerinin, uygulama içi soru-cevap mekaniklerine entegre edilebileceğini anlatın.\n\n## ❓ Sorulabilecek Stratejik 2 Soru\n1. *Yeni nesil Generative AI araçlarının (ses klonlama veya görsel üretme) çocuklar üzerindeki sosyal tehditlerini kapsayan yeni oyunlaştırılmış senaryolar tasarlamayı planlıyor musunuz?*\n2. *Uygulamanızdaki mevcut görsel dilin ve karakter tasarımlarının, uluslararası pazarlara (farklı kültürlerdeki çocuklara) hitap ederken kültürel lokalizasyona (cultural adaptation) ihtiyacı olduğunu düşünüyor musunuz?*",
      "why_recommended_tr": "Çocuklara güvenli telefon kullanımı ve sosyal medya okuryazarlığı kazandıran bu oyunlaştırılmış ürün, Serhat Bey'in 'Dijital Antropoloji' odaklı dijital sosyalleşme araştırmalarıyla ve Duygu Hanım'ın görsel evren yaratma becerileriyle inanılmaz bir sinerji oluşturur.",
      "why_recommended_en": "This gamified product teaching safe smartphone usage and social media literacy holds incredible synergy with Serhat's 'Digital Anthropology' research on digital socialization and Duygu's visual universe creation skills.",
      "strengths_tr": "Serhat Bey'in okulsuz eğitim (unschooling) ve bağlanıcılık teorilerini dijital vatandaşlığa entegre edebilmesi. Duygu Hanım'ın karakter ve illüstrasyon tecrübesinin uygulama içi hikayelere değer katması.",
      "strengths_en": "Serhat's ability to integrate unschooling and connectivism theories into digital citizenship. Duygu's character and illustration experience adding value to in-app stories.",
      "weaknesses_tr": "Halihazırda oturmuş bir UI/UX dilleri var. Duygu Hanım'ın mevcut tasarımı baştan yapmak yerine ek paketler, yeni modüller (örneğin AI riskleri modülü) için illüstrasyon üretmesi hedeflenmelidir.",
      "weaknesses_en": "They have an established UI/UX language. Pitch should focus on extension packs (e.g., AI risks module) rather than overhauling existing design."
    }
  }
]

for c in companies:
    with open(fr"d:\CODING TOOLS\ANTIGRAVITY\dutchedtech\backend\data\temp_deep_reports\{c['id']}.json", "w", encoding="utf-8") as f:
        json.dump(c["data"], f, ensure_ascii=False, indent=2)

print("Created 5 JSON files successfully.")
